docker_apt_repo: "https://download.docker.com/linux"
docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
docker_apt_gpg_key: "{{ docker_apt_repo }}/{{ ansible_distribution | lower }}/gpg"
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_apt_repo }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

docker_group_users: [ "admin" ]
