---
- name: Directory creation
  become: true
  file:
    path: "{{ firefly.base_dir }}"
    state: directory
    mode: '0777'

- name: Template Docker-Compose file
  template:
    src: "{{ role_path }}/templates/docker-compose.yaml.j2"
    dest: "{{ firefly.base_dir }}/docker-compose.yaml"
    owner: admin
    mode: '0644'

- name: Template Firefly env file
  template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ firefly.base_dir }}/.env"
    owner: admin
    mode: '0644'

- name: Template FIDI env file
  template:
    src: "{{ role_path }}/templates/fidi.env.j2"
    dest: "{{ firefly.base_dir }}/.fidi.env"
    owner: admin
    mode: '0644'

#- name: Start Firefly-III
#  community.docker.docker_compose:
#    project_src: "{{ firefly.base_dir }}"
#    pull: true
#    state: present

- name: Template Backup Script
  template:
    src: "{{ role_path }}/templates/backup.sh.j2"
    dest: "{{ firefly.base_dir }}/backup.sh"
    owner: admin
    mode: '0755'

- name: Template backup crontab
  template:
    src: "{{ role_path }}/templates/backup-firefly-cron.j2"
    dest: "/etc/cron.d/backup-firefly"

- name: Ensure logs directory exists
  file:
    path: "/var/log/backup"
    state: directory
    mode: '0777'