- name: Update authorized keys
  ansible.posix.authorized_key:
    user: {{ adm_user }}
    state: present
    key: {{ item }}
  loop: {{ authorized_keys}}

- name: Expand LVM to disk size
  become: true
  command: "/usr/bin/expand_lvm_root"
  when: expand_lvm_root == true
