raspberry:
  hosts:
    ocelot:
      ansible_host: 192.168.1.12
      ansible_user: admin
    zero:
      ansible_host: 192.168.1.13
      ansible_user: admin

minio:
  hosts:
    minio:
      ansible_host: 192.168.1.30
      ansible_user: admin
