---
- name: Directory creation
  become: true
  file:
    path: "{{ flame.base_dir }}"
    state: directory
    mode: '0777'

- name: Template Docker-compose file
  template:
    src: "{{ role_path }}/templates/docker-compose.yaml.j2"
    dest: "{{ flame.base_dir }}/docker-compose.yaml"
    owner: admin
    mode: '0644'

- name: Start Flame Dashboard
  community.docker.docker_compose:
    project_src: "{{ flame.base_dir }}"
    pull: true
    state: present